### ISSUE TITLE
Update the schedule on startup

### ISSUE THREAD

**Issue by micolous** [chrisjrn/oscon-2012-app#2]
Because schedules change a lot, the application should update the schedule from LCA's feed on startup / periodically / on demand.

There's a JSON feed already at https://linux.conf.au/programme/schedule/json which may be mangleable to your needs.

PS: Thanks for putting this together.

**Comment by chrisjrn** [comment]
Because severe CBF on this app, the update mechanism for this app is through automated update channels like the play store.

Maybe next year.
